### PR TITLE
Investigate coverage issue

### PR DESCRIPTION
**Pull request by stevepeak**
Hey hey! I'm checking out the coverage issue https://travis-ci.org/aardvarks/itsback.at#L462

Thanks!

### CODE REVIEW

**Comment by stevepeak** [comment]
Looks like the coverage reports are not being written. Do know why `/coverage` would be missing in Travis?

**Comment by bag-man** [comment]
Hi, thanks for taking a look, I left the office before anyone responded on IRC so I will have to wait till the morning to see what you said there (if anything at all!). 

The first thing that leaped to mind was that when we run `npm test` we remove the coverage folder, however on travis we are running [this command](https://github.com/aardvarks/itsback.at/blob/master/package.json#L17). 

I noticed that the first commit that codecov failed on was when we introduced ES6 promises to the project, so perhaps that is related?

**Comment by stevepeak** [comment]
@bag-man it certainly could be an ES6 issue. The first goal here is to try to generate the reports again then can upload then to Codecov. Are you able to produce them locally?

**Comment by bag-man** [comment]
We have figured it out as discussed on IRC. Thanks for your pro-activeness!

**Pull request closed without merging**
